// <auto-generated />
using System;
using Gurtas.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gurtas.Migrations
{
    [DbContext(typeof(GurtasContext))]
    [Migration("20221021104847_seed_measureTool_data")]
    partial class seed_measureTool_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gurtas.DAL.Entities.MeasureTools", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolId"), 1L, 1);

                    b.Property<string>("Accuracy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MeasureRange")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextCalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("MeasureTools");

                    b.HasData(
                        new
                        {
                            ToolId = 1,
                            Accuracy = "0,01",
                            CalibrationDate = new DateTime(2022, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CertificateNumber = "22-4791",
                            Manufacturer = "Mitutoyo",
                            MeasureRange = "0-150",
                            Model = "",
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 976, DateTimeKind.Local).AddTicks(7),
                            NextCalibrationDate = new DateTime(2023, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(9998),
                            SerialNumber = "B22084436",
                            ToolName = "Kumpas",
                            Type = "Dijital",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Gurtas.DAL.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2412),
                            Password = "qu4lity",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2391),
                            Username = "farukeraslan"
                        },
                        new
                        {
                            UserId = 2,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2420),
                            Password = "own3r",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2419),
                            Username = "aykutozgur"
                        },
                        new
                        {
                            UserId = 3,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2426),
                            Password = "pr0duction",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2425),
                            Username = "aliyilmaz"
                        },
                        new
                        {
                            UserId = 4,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2431),
                            Password = "acc0ntting",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2429),
                            Username = "cemgulpinar"
                        },
                        new
                        {
                            UserId = 5,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2436),
                            Password = "purch4sing",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2434),
                            Username = "orhanozgur"
                        },
                        new
                        {
                            UserId = 6,
                            ModifiedDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2441),
                            Password = "log1stic",
                            RecordDate = new DateTime(2022, 10, 21, 13, 48, 46, 975, DateTimeKind.Local).AddTicks(2439),
                            Username = "farukkurtoglu"
                        });
                });

            modelBuilder.Entity("Gurtas.DAL.Entities.MeasureTools", b =>
                {
                    b.HasOne("Gurtas.DAL.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
